# Generated by the reproducible-paper-artefacts skill.
#
# The guard that decides whether this branch and this tree may build a tier
# runs first here, so a refused build says so at once, even when nothing needs
# rebuilding: Snakemake skips `onstart` when no job runs. The Snakefile's
# `onstart` runs it again, so a bare `snakemake` is gated too, and the helpers
# check the same rules at each write. It takes milliseconds.
#
#   make wip TOPIC=overlap   start wip/overlap off main (BASE=<branch> to change)
#   make notes               exploratory artefacts, on a wip branch
#   make build               manuscript artefacts, on main only
#   make pdf                 compile the manuscript with the recorder on
#   make status              what is current, stale, drifted, orphaned, unused
#   make check               the invariants; what pre-push and push-paper run
#   make methods             the methods sheet: tracked settings, review state, grids
#   make methods-ok          record that the methods text was read against the sheet
#   make deps                prove the declarations cover what the build read
#   make pull-paper          pull the paper and rescan
#   make push-paper          check, push the code, then push the paper
#   make package             ARTEFACTS.md for a replication package
#   make dag                 the artefact dependency graph
#
# Scratch work has no target. Put the script and its output under scratch/ and
# run it directly. Nothing there is stamped or committed.

SHELL := /bin/bash
PY ?= python3
TOOLS := tools
CORES ?= 4

# Read from .artefacts.toml, so each is set in one place.
SETTINGS := $(shell $(PY) $(TOOLS)/_common.py main_branch main_tex paper_dir 2>/dev/null)
MAIN := $(or $(word 1,$(SETTINGS)),main)
MAIN_TEX := $(or $(word 2,$(SETTINGS)),paper/main.tex)
PAPER := $(or $(word 3,$(SETTINGS)),paper)

BASE ?= $(MAIN)
# latexmk's engine flag. Set LATEXMK_ENGINE=-lualatex or -xelatex to match
# the compiler the Overleaf project uses.
LATEXMK_ENGINE ?= -pdf
# What the tooling writes inside the paper repo. push-paper commits these, and
# nothing else, as "regenerate artefacts".
GENERATED := artefacts notes/artefacts artefacts.sty .gitignore

# The target name goes before --config. Snakemake reads everything after
# --config as key=value pairs, so a trailing target name is swallowed as a
# malformed config entry.

.PHONY: help wip notes build pdf status check methods methods-ok deps package dag pull-paper push-paper

help:
	@sed -n 's/^#   //p' $(MAKEFILE_LIST)

# A new topic starts from main. Uncommitted changes carry over to the new
# branch, which is right when they were made on BASE and wrong when they belong
# to another wip branch, so that case is refused.
wip:
	@test -n "$(TOPIC)" || { echo "Usage: make wip TOPIC=<short-topic-name> [BASE=<branch>]"; exit 1; }
	@current=$$(git branch --show-current); \
	if [ -n "$$(git status --porcelain)" ] && [ "$$current" != "$(BASE)" ]; then \
	    echo "Uncommitted changes on $$current. Commit them there first, then run this again."; exit 1; \
	fi
	@git switch -q -c wip/$(TOPIC) $(BASE)
	@echo "Started wip/$(TOPIC) off $(BASE)."

# --------------------------------------------------------------------------
# Building
# --------------------------------------------------------------------------

notes:
	@$(PY) $(TOOLS)/build_guard.py --tier notes
	@snakemake notes --cores $(CORES) --keep-going --config tier=notes

build:
	@$(PY) $(TOOLS)/build_guard.py --tier paper
	@snakemake --cores $(CORES) --config tier=paper

# -cd matters. Without it latexmk stays in the current directory, cannot find
# artefacts.sty, and writes main.aux and friends into the code repo.
pdf:
	@latexmk $(LATEXMK_ENGINE) -recorder -cd -silent -interaction=nonstopmode -halt-on-error $(MAIN_TEX) >/dev/null 2>&1 \
	    || { grep -m5 -A3 '^!' $(basename $(MAIN_TEX)).log; exit 1; }
	@echo "compiled $(MAIN_TEX)"

# --------------------------------------------------------------------------
# Knowing what is real
# --------------------------------------------------------------------------

status:
	@$(PY) $(TOOLS)/artefact_status.py

# The methods check only warns, unless [methods] strict = true in
# .artefacts.toml. The pre-push hook of the code repo does not run it: a
# methods text that lags the code is a reason to reread the paper, not to hold
# back a code push.
check:
	@$(PY) $(TOOLS)/check_artefacts.py
	@$(PY) $(TOOLS)/artefact_status.py --check
	@$(PY) $(TOOLS)/methods.py --check

methods:
	@$(PY) $(TOOLS)/methods.py

# Run it only after the methods section has been read against `make methods`.
# It commits the review record in the paper repo; the next push-paper sends it.
methods-ok:
	@$(PY) $(TOOLS)/methods.py --ok

deps:
	@$(PY) $(TOOLS)/check_deps.py

package:
	@$(PY) $(TOOLS)/artefact_status.py --write-report

dag:
	@snakemake --filegraph all notes | dot -Tpdf > artefact-dag.pdf
	@echo "wrote artefact-dag.pdf"

# --------------------------------------------------------------------------
# The paper repo
# --------------------------------------------------------------------------

# --autostash, because a build that is not pushed yet leaves changes in the
# paper repo, and a plain rebase refuses to start with those present.
pull-paper:
	@git -C $(PAPER) pull --rebase --autostash
	@$(PY) $(TOOLS)/artefact_status.py

# This is the push coauthors see, and Overleaf refuses force pushes, so there
# is no undo. So the checks run first, and nothing is committed or pushed until
# every refusal has had its chance. Then the code goes up, so that every stamp
# in BUILD.json names a commit that exists somewhere other than this machine.
# Only then is Overleaf touched.
#
# The "regenerate artefacts" commit holds only what the tooling writes. Other
# changes in the paper repo, such as prose, need a message that says what they
# are: pass MSG="..." or commit them yourself first.
#
# Overleaf's git bridge fails in two reliable ways. A large push comes back as
# HTTP 500 and succeeds with a bigger buffer. A concurrent web edit makes the
# push non-fast-forward, and rebasing on top of it is the fix.
push-paper: check
	@$(PY) $(TOOLS)/record_provenance.py --merge >/dev/null
	@other=$$(git -C $(PAPER) status --porcelain -- . $(addprefix ':!',$(GENERATED))); \
	if [ -n "$$other" ] && [ -z "$(MSG)" ]; then \
	    echo "The paper repo has changes outside the generated files:"; echo "$$other"; \
	    echo 'Commit them with a message that says what changed, or run make push-paper MSG="..."'; \
	    exit 1; \
	fi
	@if git rev-parse --abbrev-ref --symbolic-full-name $(MAIN)@{upstream} >/dev/null 2>&1; then \
	    git push --quiet "$$(git config branch.$(MAIN).remote)" $(MAIN) && echo "code pushed ($(MAIN))"; \
	else \
	    echo "warning: $(MAIN) has no upstream, so the commits that stamp these artefacts exist only on this machine"; \
	fi
	@set -e; cd $(PAPER); \
	for p in $(GENERATED); do \
	    if [ -e "$$p" ] || git ls-files --error-unmatch -- "$$p" >/dev/null 2>&1; then git add -A -- "$$p"; fi; \
	done; \
	git diff --cached --quiet || git commit -q -m "regenerate artefacts"; \
	if [ -n "$$(git status --porcelain)" ]; then git add -A && git commit -q -m "$(MSG)"; fi; \
	err=$$(mktemp); \
	if ! git push 2>$$err; then \
	    if grep -qi '500' $$err; then \
	        echo "Overleaf returned 500, retrying with a larger buffer"; \
	        git -c http.postBuffer=524288000 push; \
	    elif grep -qi 'non-fast-forward\|rejected\|fetch first' $$err; then \
	        echo "Overleaf moved ahead, rebasing onto it"; \
	        git pull --rebase && git push; \
	    else \
	        cat $$err >&2; rm -f $$err; exit 1; \
	    fi; \
	fi; \
	rm -f $$err; \
	echo "paper pushed"
