# Generated by the reproducible-paper-artefacts skill. Edit freely; the rules
# below are a worked skeleton, not a fixed contract.

from glob import glob
from pathlib import Path
import os
import subprocess
import sys

ART = "paper/artefacts"
NOTES = "paper/notes/artefacts"

# Python scripts import the helpers with `import artefacts`. Snakemake runs each
# script under its own interpreter and puts only the script's folder on
# sys.path, so the helper folder goes on PYTHONPATH here, where `make` and a
# bare `snakemake` both pass. That interpreter is also where a Python rule's
# packages must be installed (for a uv install of Snakemake:
# `uv tool install snakemake --with pandas`), unless the rule has a `conda:`
# environment.
os.environ["PYTHONPATH"] = os.pathsep.join(
    p for p in (str(Path("py/lib").resolve()), os.environ.get("PYTHONPATH")) if p
)

# The registry: every artefact the manuscript uses. Empty to start, so a first
# `make build` succeeds with nothing to do. A name here without a rule below
# fails at once with MissingRuleException, so this list is safe to treat as the
# registry.
NUMBERS: list[str] = []
FIGURES: list[str] = []
TABLES: list[str] = []

# Exploratory output. Deliberately not part of `rule all`: a manuscript build
# should not drag along months of abandoned exploration.
NOTES_NUMBERS: list[str] = []
NOTES_FIGURES: list[str] = []
NOTES_TABLES: list[str] = []


def lib(*dirs):
    """Every file under these topic directories, as rule inputs.

    Snakemake's `code` rerun trigger hashes the script file and nothing it
    sources or imports. Change a function in R/lib/estimate and the script
    hashes the same, so Snakemake reports the artefact as up to date when it is
    not. A false-fresh number is worse than no tracking at all, because it is
    the kind of wrong you stop checking for.

    Declaring the directory fixes that without per-file bookkeeping. New helper
    files are picked up automatically, and invalidation is coarse in the safe
    direction: editing any estimation helper marks every fit stale, and nothing
    that read a file is ever missed.

    The lever on precision is directory structure. If R/lib/estimate is too
    blunt, split it into estimate/ipw and estimate/tmle and have each rule
    depend on what it uses.
    """
    out = []
    for d in dirs:
        # A single file is a legitimate argument. Globbing "file.R/**/*" matches
        # nothing, so without this a lib("R/lib/artefacts.R") would silently
        # declare no dependency at all, which is the exact silent
        # under-declaration this helper exists to prevent.
        if Path(d).is_file():
            out.append(d)
            continue
        for f in glob(f"{d}/**/*", recursive=True):
            q = Path(f)
            if not q.is_file():
                continue
            # Compiled bytecode and editor droppings are not source. They also
            # change every time the interpreter runs, so declaring them would
            # mark artefacts stale for no reason and train you to ignore the
            # staleness report.
            if any(part.startswith(".") or part == "__pycache__" for part in q.parts):
                continue
            if q.suffix in {".pyc", ".pyo", ".so", ".o", ".rdb", ".rdx"}:
                continue
            out.append(f)
    return sorted(out)


EST = lib("R/lib/estimate", "R/lib/artefacts.R")
PLOT = lib("R/lib/plot", "R/lib/artefacts.R")
SIM = lib("py/lib/sim", "py/lib/artefacts.py")


onstart:
    # The Makefile already ran this, with a friendlier message. Running it again
    # here is what closes the bypass: a bare `snakemake` gets guarded too. With
    # no tier given the strictest one applies, so the bypass fails closed.
    tier = config.get("tier", "paper")
    result = subprocess.run(
        [sys.executable, "tools/build_guard.py", "--tier", tier],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        sys.exit(result.stdout + result.stderr)


onsuccess:
    # Collapse the per-rule provenance sidecars into BUILD.json. It lives here
    # rather than in the Makefile so that a bare `snakemake` produces exactly
    # the same result, which leaves `make` as convenience rather than as a step
    # you can forget.
    subprocess.run([sys.executable, "tools/record_provenance.py", "--merge"])


onerror:
    # A build that fails part way has still written some artefacts, and
    # BUILD.json should describe them.
    subprocess.run([sys.executable, "tools/record_provenance.py", "--merge"])


rule all:
    input:
        expand(f"{ART}/numbers/{{u}}.tex", u=NUMBERS),
        expand(f"{ART}/figures/{{f}}.pdf", f=FIGURES),
        expand(f"{ART}/tables/{{t}}.tex", t=TABLES),
        *([f"{ART}/artefacts.tex"] if NUMBERS else []),


rule notes:
    input:
        expand(f"{NOTES}/numbers/{{u}}.tex", u=NOTES_NUMBERS),
        expand(f"{NOTES}/figures/{{f}}.pdf", f=NOTES_FIGURES),
        expand(f"{NOTES}/tables/{{t}}.tex", t=NOTES_TABLES),


rule artefacts_tex:
    """One \\input line for main.tex, regenerated as numbers come and go.

    The preamble says \\input{artefacts/artefacts.tex} once and never changes.
    """
    input:
        expand(f"{ART}/numbers/{{u}}.tex", u=NUMBERS),
    output:
        f"{ART}/artefacts.tex",
    run:
        lines = ["% Generated. Do not edit.", ""]
        lines += ["\\input{artefacts/numbers/%s}" % Path(p).name for p in sorted(input)]
        Path(output[0]).write_text("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# A worked example, commented out. Uncomment, adjust the paths, and add the
# artefact names to the lists at the top.
#
# The shape that matters is the two-layer split. Everything expensive writes a
# results file, and the figures, tables and numbers depend on that file plus
# the presentation helpers. Without the split, fixing a typo in a plotting
# comment re-runs the Monte Carlo, and a pipeline that charges an hour for a
# cosmetic change is one people stop using.
#
# Add `conda: "envs/py.yaml"` to a rule once you have an environment file, so
# that a dependency bump marks the affected artefacts stale.
#
# rule simulate_primary:                      # expensive: runs once
#     input:
#         dgp="config/dgp.yaml",
#         helpers=SIM,
#     output:
#         "results/sim-primary.parquet",
#     threads: 8
#     script: "py/simulate_primary.py"
#
# rule fig_primary:                           # cheap: re-renders in seconds
#     input:
#         results="results/sim-primary.parquet",
#         helpers=PLOT,
#     output:
#         f"{ART}/figures/fig-primary.pdf",
#     script: "R/fig_primary.R"
#
# rule fit_primary:
#     input:
#         data="data/analysis.rds",
#         helpers=EST,
#     output:
#         fit="results/fit-primary.rds",
#         numbers=f"{ART}/numbers/primary-fit.tex",
#     script: "R/fit_primary.R"
